runtime: nodejs20
service: default
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.5
  target_throughput_utilization: 0.5
  max_concurrent_requests: 80

includes:
  #- env_variables.yaml

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
